// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5D1ufvPF4tSKZ8At_20EFj8BuLN_ZeCY',
    appId: '1:193447783777:web:f9bc2e67025e3508c8a920',
    messagingSenderId: '193447783777',
    projectId: 'befit-8fb5b',
    authDomain: 'befit-8fb5b.firebaseapp.com',
    storageBucket: 'befit-8fb5b.appspot.com',
    measurementId: 'G-XWJQYQMNDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7O5ChzjRePjFRxFWqJaWRUPkN3xGkMX4',
    appId: '1:193447783777:android:8bf52c6025ee22cec8a920',
    messagingSenderId: '193447783777',
    projectId: 'befit-8fb5b',
    storageBucket: 'befit-8fb5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rTfOtbJrUpGlYWb8gVw3LR7PbTu_aBo',
    appId: '1:193447783777:ios:b5d7596860f69731c8a920',
    messagingSenderId: '193447783777',
    projectId: 'befit-8fb5b',
    storageBucket: 'befit-8fb5b.appspot.com',
    iosClientId: '193447783777-lp7c1c5mifrh2meuhercf2oqq21497r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmicalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9rTfOtbJrUpGlYWb8gVw3LR7PbTu_aBo',
    appId: '1:193447783777:ios:b5d7596860f69731c8a920',
    messagingSenderId: '193447783777',
    projectId: 'befit-8fb5b',
    storageBucket: 'befit-8fb5b.appspot.com',
    iosClientId: '193447783777-lp7c1c5mifrh2meuhercf2oqq21497r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmicalc',
  );
}
